version: "3"
services:
  hub:
    container_name: hub
    image: selenium/hub:3.141.59
    privileged: true
    ports: 
      - 4444:4444
    environment:
      - GRID_BROWSER_TIMEOUT=240000
      - GRID_TIMEOUT=240000
  chrome:
    container_name: node-chrome
    image: selenium/node-chrome-debug:3.141.59
    privileged: true
    ports: 
      - 5900
    shm_size: 256M
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - no_proxy=localhost
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
  testapp:
    container_name: testapp
    build: .
    image: dneprokos/testapp
    ports:               
      - "4200:4200"
    volumes:
      - /var/jenkins_home/workspace/test:/app/e2e/results
    depends_on:             
      - chrome
      - hub