pipeline {
  agent any
  triggers {
    pollSCM('* * * * *') /* validate repository once per mniute and pull if there is changes */
  }
  environment { 
    ADMIN_NAME = 'Kostiantyn Teltov' /* variables on pipeline level */
  }
  options {
    disableConcurrentBuilds() /* Disallow concurrent executions of the Pipeline. 
    Can be useful for preventing simultaneous accesses to shared resources, etc */
    retry(1) /* On failure, retry the entire Pipeline the specified number of times. */
    skipStagesAfterUnstable() /* Skip stages once the build status has gone to UNSTABLE. */
    timeout(time: 30, unit: 'MINUTES') /* Set a timeout period for the Pipeline run, after which Jenkins should abort the Pipeline. */
    timestamps() /* Prepend all console output generated by the Pipeline run with the time at which the line was emitted. */  
  }
  parameters {
    string(name: 'PERSON', defaultValue: "Mr ADMIN", description: 'Who should I say goodbye to?')
  } /* A few other data types can be used for the parameters. Please find reference here: https://jenkins.io/doc/book/pipeline/syntax/ */
  stages {
    stage('Prepare workspace') {
      options { /* You may also define options per stage. But it has limited amount of supported methods */
        timeout(time: 10, unit: 'MINUTES')
      }
      steps {
        echo 'Hello ${ADMIN_NAME}. We are starting to cleanup workspace.'
        deleteDir() /* clean up our workspace */
      }
    }
    stage('Build/Deploy') {
      steps {
        echo 'Start deployment'
      }
    }
    stage('Run e2e tests') {
      environment { 
        TEST_TYPES = 'e2e' /* variables on pipeline stage level */
      }
      steps {
        echo 'Starting to run ${TEST_TYPES} tests'
      }
    }
    stage('Deploy to production') {
      when {
        beforeInput true
        branch 'master'
      }
      input {
        message "Should we deploy on production?"
        ok "Deploy!"
      }
      steps {
        echo 'Start deployment to Production'
      }
    }
  }
  post {
        always {
            echo 'This is Always post step example. Thanks for using Jenkins. Goodbye ${params.PERSON}'          
        }
        success {
            echo 'This is example of sucess step'
        }
        failure {
            echo 'This is example of failure step'
        }
        cleanup {
            echo 'This is example of cleanup step'
        }
  } /* Pipeline may contain a lot of other post steps. Please find reference here: https://jenkins.io/doc/book/pipeline/syntax/ */
}