version: "3"
services:
  master:
    container_name: ${JENKINS_MASTER_NAME}
    build: ./DockerMasterTemplate
    user: root
    env_file: .env
    ports:
      - ${MAP_PORT_WINDOWS}:8080
      - 50000:50000
    environment:
      - JAVA_OPTS=-Xmx2048m
      - JENKINS_SLAVE_AGENT_PORT=50000
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    volumes:
      - ${USER_HOME_WINDOWS}/jenkins-data:/var/jenkins_home
      - ${USER_HOME_WINDOWS}:/home
      - /var/run/docker.sock:/var/run/docker.sock
  slavedockerssh:
    container_name: ${JENKINS_SLAVE_SSH_NAME}
    build: ./DockerSlaveTemplate
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=${SSH_PUBLIC}
